# Generated by Django 4.1.5 on 2023-01-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card_Cars',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID объявления')),
                ('user_id', models.IntegerField(verbose_name='ID пользователя')),
                ('brand', models.CharField(max_length=250, verbose_name='Марка автомобиля')),
                ('model', models.CharField(max_length=250, verbose_name='Модель автомобиля')),
                ('about', models.TextField(verbose_name='Описание автомобиля')),
                ('city_sale', models.CharField(max_length=250, verbose_name='Населенный пункт продажи')),
                ('date', models.DateTimeField(max_length=250, verbose_name='Дата и время публикации')),
                ('color', models.CharField(max_length=250, verbose_name='Цвет автомобиля')),
                ('engine', models.CharField(max_length=250, verbose_name='Название двигателя')),
                ('power', models.IntegerField(verbose_name='Мощность автомобиля')),
                ('car_number', models.CharField(max_length=250, verbose_name='Номер автомобиля')),
                ('vin_number', models.CharField(max_length=250, verbose_name='Вин номер автомобиля')),
                ('millage', models.IntegerField(verbose_name='Пробег автомобиля')),
                ('transmission', models.CharField(max_length=250, verbose_name='Привод автомобиля')),
            ],
        ),
    ]
