# Generated by Django 4.1.5 on 2023-01-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card_cars',
            options={'verbose_name': 'Карточка автомобиля', 'verbose_name_plural': 'Карточки автомобилей'},
        ),
        migrations.AddField(
            model_name='card_cars',
            name='price',
            field=models.IntegerField(default=100000, verbose_name='Цена автомобиля'),
            preserve_default=False,
        ),
    ]
