# Generated by Django 4.1.5 on 2023-01-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_model_and_brand_cars'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands_Cars',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=250, verbose_name='Марка автомобиля')),
            ],
            options={
                'verbose_name': 'Марка автомобиля',
                'verbose_name_plural': 'Марки автомобилей',
            },
        ),
    ]
